version: '3.3'

volumes:
  pg_data:
  pgadmin_data:

networks:
  backend_net:

services:
  postgres:
    image: postgres:13
    restart: unless-stopped
    environment:
      - POSTGRES_DB=hatoverde
      - POSTGRES_USER=jlosada
      - POSTGRES_PASSWORD=r00t123
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - '5432:5432'
    volumes:
      - ./pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD', 'pg_isready', '-U', 'jlosada']
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - backend_net

  pgadmin:
    image: dpage/pgadmin4
    restart: unless-stopped
    depends_on:
      - postgres
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@mail.com
      - PGADMIN_DEFAULT_PASSWORD=r00t123
    ports:
      - '5050:80'
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    networks:
      - backend_net
